/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountAdd: typeof import('./src/components/AccountAdd.vue')['default']
    AccountItem: typeof import('./src/components/AccountItem.vue')['default']
    AccountList: typeof import('./src/components/AccountList.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
  }
}
